name: ci

env:
  CTEST_PARALLEL_LEVEL: 3
  CMAKE_BUILD_TYPE: Release

on:
  push:
    paths:
      - "**/CMakeLists.txt"
      - "**.cmake"
      - "**.c"
      - "**.f90"
      - ".github/workflows/ci.yml"
  release:
    types: [published]


jobs:

  linux:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v2

    - name: install prerequisites
      run: |
        sudo apt update -yq
        sudo apt install -yq --no-install-recommends libhwloc-dev

    - run: cmake -B build
    - run: cmake --build build
    - run: ctest --test-dir build --preset default --output-junit test-results.xml

    - name: Publish Unit Test Results
      uses: EnricoMi/publish-unit-test-result-action@v1
      if: always()
      with:
        files: build/test-results.xml

  linux-build:
    needs: linux
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v2

    - run: cmake -B build
    - run: cmake --build build
    - run: ctest --test-dir build --preset default


  mac:
    needs: linux
    runs-on: macos-latest
    timeout-minutes: 15
    env:
      HOMEBREW_NO_INSTALL_CLEANUP: 1
      FC: gfortran-11

    steps:
    - uses: actions/checkout@v2

    - run: brew install hwloc

    - run: cmake -B build
    - run: cmake --build build
    - run: ctest --test-dir build


  mac-build:
    needs: mac
    runs-on: macos-latest
    timeout-minutes: 15
    env:
      HOMEBREW_NO_INSTALL_CLEANUP: 1
      FC: gfortran-11

    steps:
    - uses: actions/checkout@v2

    - run: brew install autoconf automake libtool

    - run: cmake -B build
    - run: cmake --build build
    - run: ctest --test-dir build

  msys2:
    needs: linux
    timeout-minutes: 15
    runs-on: windows-latest
    env:
      CMAKE_GENERATOR: Ninja

    defaults:
      run:
        shell: msys2 {0}
    steps:
    - uses: msys2/setup-msys2@v2
      with:
        update: true
        install: >-
          git
          mingw-w64-x86_64-cmake
          mingw-w64-x86_64-ninja
          mingw-w64-x86_64-gcc-fortran
          mingw-w64-x86_64-hwloc
    # cmake install needed because of default to msys2 shell

    - uses: actions/checkout@v2

    - run: cmake -B build
    - run: cmake --build build
    - run: ctest --test-dir build --output-junit test-results.xml
